version: '3.9'

services:
  app:
    container_name: localdev
    image: localdev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    # environment:
    #   # - GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}
    #   # - PORT=${PORT}
    #   - REACT_APP_HOST_API_KEY=${REACT_APP_HOST_API_KEY}
